import type { MigrationBuilder } from 'node-pg-migrate';

export function up(pgm: MigrationBuilder): void {
  pgm.sql(`
    CREATE TABLE mqtt_connections (
      id UUID PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      broker_url TEXT NOT NULL,
      port INTEGER NOT NULL CHECK (port BETWEEN 1 AND 65535),
      use_tls BOOLEAN NOT NULL DEFAULT FALSE,
      username TEXT,
      encrypted_password TEXT,
      client_id_prefix VARCHAR(100),
      enabled BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE TABLE devices (
      id VARCHAR(100) PRIMARY KEY,
      name VARCHAR(150) NOT NULL,
      mqtt_connection_id UUID NOT NULL REFERENCES mqtt_connections(id) ON DELETE RESTRICT,
      telemetry_topic TEXT NOT NULL,
      command_topic TEXT NOT NULL,
      response_topic TEXT NOT NULL,
      offline_after_seconds INTEGER NOT NULL DEFAULT 20 CHECK (offline_after_seconds > 0),
      enabled BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE (mqtt_connection_id, telemetry_topic),
      UNIQUE (mqtt_connection_id, command_topic)
    );

    CREATE TABLE telemetry (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      device_id VARCHAR(100) NOT NULL REFERENCES devices(id) ON DELETE RESTRICT,
      temperature DOUBLE PRECISION NOT NULL,
      humidity DOUBLE PRECISION NOT NULL,
      coil_temperature DOUBLE PRECISION NOT NULL,
      humidity_setpoint DOUBLE PRECISION NOT NULL,
      temperature_setpoint DOUBLE PRECISION NOT NULL,
      running_status VARCHAR(50) NOT NULL,
      running_mode VARCHAR(50) NOT NULL,
      water_tank_status VARCHAR(50) NOT NULL,
      sensor_error INTEGER NOT NULL,
      received_at TIMESTAMPTZ NOT NULL
    );

    CREATE INDEX idx_telemetry_device_received_at
      ON telemetry (device_id, received_at DESC);

    CREATE TABLE command_logs (
      id UUID PRIMARY KEY,
      device_id VARCHAR(100) NOT NULL REFERENCES devices(id) ON DELETE RESTRICT,
      mqtt_payload TEXT NOT NULL,
      status VARCHAR(20) NOT NULL CHECK (status IN ('pending', 'success', 'timeout', 'error')),
      response TEXT,
      created_at TIMESTAMPTZ NOT NULL,
      completed_at TIMESTAMPTZ
    );

    CREATE INDEX idx_command_logs_device_created_at
      ON command_logs (device_id, created_at DESC);

    CREATE TABLE event_logs (
      id UUID PRIMARY KEY,
      device_id VARCHAR(100) NOT NULL REFERENCES devices(id) ON DELETE RESTRICT,
      type VARCHAR(100) NOT NULL,
      severity VARCHAR(20) NOT NULL CHECK (severity IN ('info', 'warning', 'danger')),
      message TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL
    );

    CREATE INDEX idx_event_logs_device_created_at
      ON event_logs (device_id, created_at DESC);
  `);
}

export function down(pgm: MigrationBuilder): void {
  pgm.sql(`
    DROP TABLE IF EXISTS event_logs;
    DROP TABLE IF EXISTS command_logs;
    DROP TABLE IF EXISTS telemetry;
    DROP TABLE IF EXISTS devices;
    DROP TABLE IF EXISTS mqtt_connections;
  `);
}
